// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermostat.proto

package thermostat;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
