// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermostat.proto

package thermostat;

public final class ThermostatServiceImpl {
  private ThermostatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_TemperatureRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020thermostat.proto\022\nthermostat\"\035\n\014PowerR" +
      "equest\022\r\n\005state\030\001 \001(\010\"\036\n\rPowerResponse\022\r" +
      "\n\005state\030\001 \001(\010\"#\n\023TemperatureResponse\022\014\n\004" +
      "temp\030\001 \001(\005\"\"\n\022TemperatureRequest\022\014\n\004temp" +
      "\030\001 \001(\0052\256\001\n\021ThermostatService\022>\n\005power\022\030." +
      "thermostat.PowerRequest\032\031.thermostat.Pow" +
      "erResponse\"\000\022Y\n\021changeTemperature\022\037.ther" +
      "mostat.TemperatureResponse\032\037.thermostat." +
      "TemperatureResponse\"\0000\001B%\n\nthermostatB\025T" +
      "hermostatServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_thermostat_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_thermostat_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_thermostat_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_thermostat_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_thermostat_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_thermostat_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_TemperatureResponse_descriptor,
        new java.lang.String[] { "Temp", });
    internal_static_thermostat_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_thermostat_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_TemperatureRequest_descriptor,
        new java.lang.String[] { "Temp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
