// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package light;

public final class LightServiceImpl {
  private LightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_LightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_BrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_BrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_BrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_BrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lights.proto\022\006lights\"\035\n\014LightRequest\022\r" +
      "\n\005state\030\001 \001(\010\"\036\n\rLightResponse\022\r\n\005state\030" +
      "\001 \001(\010\"\'\n\021BrightnessRequest\022\022\n\nbrightness" +
      "\030\001 \001(\005\"(\n\022BrightnessResponse\022\022\n\nbrightne" +
      "ss\030\001 \001(\0052\230\001\n\014LightService\0229\n\010lightsOn\022\024." +
      "lights.LightRequest\032\025.lights.LightRespon" +
      "se\"\000\022M\n\020changeBrightness\022\031.lights.Bright" +
      "nessRequest\032\032.lights.BrightnessResponse\"" +
      "\000(\001B\033\n\005lightB\020LightServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lights_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lights_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_LightRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_lights_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lights_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_LightResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_lights_BrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lights_BrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_BrightnessRequest_descriptor,
        new java.lang.String[] { "Brightness", });
    internal_static_lights_BrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lights_BrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_BrightnessResponse_descriptor,
        new java.lang.String[] { "Brightness", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
