// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package light;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
