// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphone.proto

package microphone;

public interface MicrophoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:microphone.MicrophoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string audio = 1;</code>
   */
  java.lang.String getAudio();
  /**
   * <code>string audio = 1;</code>
   */
  com.google.protobuf.ByteString
      getAudioBytes();
}
