// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphone.proto

package microphone;

public final class MicrophoneServiceImpl {
  private MicrophoneServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_microphone_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_microphone_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_microphone_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_microphone_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_microphone_MicrophoneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_microphone_MicrophoneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_microphone_MicrophoneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_microphone_MicrophoneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020microphone.proto\022\nmicrophone\"\035\n\014PowerR" +
      "equest\022\r\n\005state\030\001 \001(\010\"\036\n\rPowerResponse\022\r" +
      "\n\005state\030\001 \001(\010\"\"\n\021MicrophoneRequest\022\r\n\005au" +
      "dio\030\001 \001(\t\"#\n\022MicrophoneResponse\022\r\n\005audio" +
      "\030\001 \001(\t2\261\001\n\021MicrophoneService\022@\n\007powerOn\022" +
      "\030.microphone.PowerRequest\032\031.microphone.P" +
      "owerResponse\"\000\022Z\n\023microphoneRecording\022\035." +
      "microphone.MicrophoneRequest\032\036.microphon" +
      "e.MicrophoneResponse\"\000(\0010\001B%\n\nmicrophone" +
      "B\025MicrophoneServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_microphone_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_microphone_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_microphone_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_microphone_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_microphone_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_microphone_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_microphone_MicrophoneRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_microphone_MicrophoneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_microphone_MicrophoneRequest_descriptor,
        new java.lang.String[] { "Audio", });
    internal_static_microphone_MicrophoneResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_microphone_MicrophoneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_microphone_MicrophoneResponse_descriptor,
        new java.lang.String[] { "Audio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
