// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphone.proto

package microphone;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:microphone.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
