// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package laptop;

public interface BrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laptop.BrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightness = 1;</code>
   */
  int getBrightness();
}
