// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package laptop;

public final class LaptopServiceImpl {
  private LaptopServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptop_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laptop_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptop_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laptop_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptop_BrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laptop_BrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laptop_BrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laptop_BrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014laptop.proto\022\006laptop\"\035\n\014PowerRequest\022\r" +
      "\n\005state\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005state\030" +
      "\001 \001(\010\"\'\n\021BrightnessRequest\022\022\n\nbrightness" +
      "\030\001 \001(\005\"(\n\022BrightnessResponse\022\022\n\nbrightne" +
      "ss\030\001 \001(\0052\230\001\n\rLaptopService\0228\n\007powerOn\022\024." +
      "laptop.PowerRequest\032\025.laptop.PowerRespon" +
      "se\"\000\022M\n\020changeBrightness\022\031.laptop.Bright" +
      "nessRequest\032\032.laptop.BrightnessResponse\"" +
      "\000(\001B\035\n\006laptopB\021LaptopServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_laptop_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_laptop_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laptop_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_laptop_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_laptop_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laptop_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_laptop_BrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_laptop_BrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laptop_BrightnessRequest_descriptor,
        new java.lang.String[] { "Brightness", });
    internal_static_laptop_BrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_laptop_BrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laptop_BrightnessResponse_descriptor,
        new java.lang.String[] { "Brightness", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
