// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package laptop;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laptop.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
